### ISSUE TITLE
"logging" requirement 

### ISSUE THREAD

**Issue by RobThePCGuy** [MaxSSD/OpenAI-widget#6]
[logging](https://docs.python.org/3/library/logging.html) is part of the built in Python libs since 2.3ish. At least as of the version I"m on it'll pop an error when installing the requirements.txt. 3.11

**Comment by MaxSSD** [comment]
> [logging](https://docs.python.org/3/library/logging.html) is part of the built in Python libs since 2.3ish. At least as of the version I"m on it'll pop an error when installing the requirements.txt. 3.11

Thanks for bringing it up just deleted the line. I run python code with Python 3.9 or earlier.
